<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="ClosedXML" Version="0.105.0" />
      <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.16">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="9.0.16" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.16">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="Views\MainWindow.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\Icon.ico" />
      <Resource Include="Resources\Icon.ico" />
      <None Remove="Resources\10.jpg" />
      <Resource Include="Resources\10.jpg" />
      <None Remove="Resources\9.jpg" />
      <Resource Include="Resources\9.jpg" />
      <None Remove="Resources\picture.png" />
      <Resource Include="Resources\picture.png" />
      <None Remove="Resources\8.jpg" />
      <Resource Include="Resources\8.jpg" />
      <None Remove="Resources\7.jpg" />
      <Resource Include="Resources\7.jpg" />
      <None Remove="Resources\6.jpg" />
      <Resource Include="Resources\6.jpg" />
      <None Remove="Resources\5.jpg" />
      <Resource Include="Resources\5.jpg" />
      <None Remove="Resources\4.jpg" />
      <Resource Include="Resources\4.jpg" />
      <None Remove="Resources\3.jpg" />
      <Resource Include="Resources\3.jpg" />
      <None Remove="Resources\1.jpg" />
      <Resource Include="Resources\1.jpg" />
      <None Remove="Resources\2.jpg" />
      <Resource Include="Resources\2.jpg" />
      <None Remove="Resources\Icon.png" />
      <Resource Include="Resources\Icon.png" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\user_import.xlsx" />
      <Content Include="Resources\user_import.xlsx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <None Remove="Resources\Tovar.xlsx" />
      <Content Include="Resources\Tovar.xlsx">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

</Project>
